<!--http://www.w3.org/2001/XMLSchema-->

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://soap.jee.mcnz.com/"
            targetNamespace="http://soap.jee.mcnz.com/" elementFormDefault="qualified">

    <xs:complexType name="User">
        <xs:sequence>
            <xs:element name="id" type="xs:long" nillable="true"/>
            <xs:element name="firstName" type="xs:string"/>
            <xs:element name="userName" type="xs:string"/>
            <xs:element name="primaryRole" type="xs:string"/>
            <xs:element name="isAdmin" type="xs:boolean"/>
            <xs:element name="birthdate" type="xs:date"/>
        </xs:sequence>
    </xs:complexType>

    <!-- CREATE -->
    <xs:element name="addUserRequest">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="user" type="tns:User"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="addUserResponse">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="status" type="xs:string"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <!-- READ -->
    <xs:element name="getUserRequest">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="id" type="xs:long"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="getUserResponse">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="user" type="tns:User"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="getAllUsersRequest">
        <xs:complexType>
            <xs:sequence/>
        </xs:complexType>
    </xs:element>

    <xs:element name="getAllUsersResponse">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="users" type="tns:User" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="getUsersByPrimaryRoleRequest">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="primaryRole" type="xs:string"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="getUsersByPrimaryRoleResponse">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="users" type="tns:User" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <!-- UPDATE -->
    <xs:element name="updateUserRequest">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="user" type="tns:User"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="updateUserResponse">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="status" type="xs:string"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <!-- DELETE -->
    <xs:element name="deleteUserRequest">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="id" type="xs:long"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="deleteUserResponse">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="status" type="xs:string"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>